apiVersion: v1
kind: ConfigMap
metadata:
  name: oasis-config
data:
  DB_USER: "root"
  DB_NAME: "oasisdb"
  DB_PORT: "3306"
  NODE_ENV: "production"
  FRONTEND_URL: "http://oasis-frontend:80"
  BACKEND_PORT: "4000"
  USE_MYSQL: "true"
