apiVersion: v1
kind: Service
metadata:
  name: oasis-frontend
spec:
  type: NodePort
  selector:
    app: oasis-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: oasis-backend
spec:
  type: NodePort
  selector:
    app: oasis-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30400
---
apiVersion: v1
kind: Service
metadata:
  name: oasis-db
spec:
  type: ClusterIP
  selector:
    app: oasis-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
